### ISSUE TITLE
Apples

### ISSUE THREAD

**Issue by gstempel** [atolen/Yutta-Hey#2]
Do you know the apple man,
the apple man, the apple man?
Do you know the apple man?
He planted apple seeds.

He wore a pot upon his head,
upon his head, upon his head.
He wore a pot upon his head.
His name was Johnny Appleseed.

John Chapman was his real name,
his real name, his real name.
John Chapman was his real name;
But, we call him Johnny Appleseed.

**Comment by heathenprince** [comment]
Sounds like a nut. Stay away from this man.
